name: AT-AT-Pull-Request-Terraform-Plan2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        type: environment
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    uses: .github/workflows/atat-terraform-core-workflow.yaml
    with:
      environment: ${{ github.event.inputs.environment }}